---
- name: "playbook for build docker compose"
  hosts: localhost
  tasks:
    - name: "remove conatiners"
      command: dokcer compose down
      ignore_errors: yes
    - name: "remove php image"
      command: docker image remove aminabaza/onlineshoping
      ignore_errors: yes
    - name: "remove phpmyadmin image"
      command: docker image remove phpmyadmin/phpmyadmin
      ignore_errors: yes
    - name: "remove mysql image"
      command: docker image remove mysql:5.7
      ignore_errors: yes
    - name: "build images and containers for website"
      command: docker compose up -d